### ISSUE TITLE
can't get it to work under Arduino IDE 1.8.19 and latest library-updates

### ISSUE THREAD

**Issue by heinerolli** [JChristensen/serialLogger#1]
I hope you still see this, as its a rather old project....

I used your code w/ an UNO and a Data-Logging hat
It compiles fine, but when I start it, the LEDs briefly flash (as per your loop in setup(), but then nothing. no heartbeat LED pulsing - nothing.

Is there any way I can touble shoot this? Does it work for you when you complile with IDE 1.8.x and latest libraries?
(I have installed your JC_Button library and included "buffer.h" and "heartbeat.h" in the sketch folder)
I am not using a rotary switch, but hardcode the baud rate with uint32_t USART0_BAUDRATE = 57600; // was:  baudRates[baudIdx];
Unfortunately, the important parts of your code I do not understand completely....

Any help would be great!

**Comment by JChristensen** [comment]
Hi @heinerolli,

Without understanding the hardware and code changes, it's pretty difficult to speculate as to what the issue might be.

FWIW, the sketch compiles clean for me with Arduino IDE 1.8.19 and all the latest libraries. I uploaded it to one of my boards and it seems to function OK.

Good luck ... jc

**Comment by heinerolli** [comment]
Hi @JChristensen ;
Thank you for the reply and confirmation that it works for you w/ latest IDE & libraries.
That helps for my troubleshooting.

Wrt code changes: I only changed the stated line "uint32_t USART0_BAUDRATE = 57600; // was: baudRates[baudIdx];"
to have a fixed baud rate. Nothing else.
Wrt hardware: I dont have the rotary switch and the SD card hat is connected w/ the std. pins 10-13 (And I verified w/ other code that it does work using the SdFat lib)

What puzzles me most is that after the setup() 'blink' of the LEDs (which works), there is no further LED blinking happening.
If I understand your descrtiption (see below) right, there should be some sort of blinking going on in any case, right?
Or is by 'Short blink' just the 1 time setup() 'blink' meant?

//  Short blink: Idle mode.
//  Steady blink on/off: Logging.
//  Fast blink on/off: Error.
//  Slow on/off: No SD card inserted.

**Comment by heinerolli** [comment]
Hi @JChristensen ;
this is embarrassing.... the code worked all along... I had just at this early stage of my project only 2 LEDs connected:
I thought I had connected  SD_LED and HB_LED, but in fact I had connected OVR_LED and SD_LED ... 
So, obviously - no heart beat was visible....
Now it works as expected.
-> Sorry to have wasted your time and thank you for this great Serial Logger!

**Comment by JChristensen** [comment]
Hi again,
Haha, no worries, it happens to us all!
Glad you have it sorted out, hope it works well for you.
Cheers ... jc
